In [1]:
import numpy as np

In [3]:
roll=np.array([1,2,3,4,5,6,7,8,9,10])
g=(['M','F','M','M','F','F','F','M','null','null'])
marks=np.array([12,23,34,45,67,56,78,89,90,100])
att=np.array([12,23,34,45,56,67,78,89,90,100])

In [5]:
np.sum(g=='null')

np.int64(0)

In [7]:
l=[]
import random
for i in range(13):
    a=random.randint(0,30)
    l.append(a)
print(l)
np.random.randn(0,30)

[19, 14, 21, 27, 21, 20, 0, 25, 4, 14, 5, 15, 20]

array([], shape=(0, 30), dtype=float64)

In [8]:
import pandas as pd

In [9]:
df=pd.read_csv(r'C:\Users\jainm\OneDrive\ドキュメント\college notes\patient_details.csv')
df

    patient_id          name   age  gender     city admission_date height_cm
0         P001           NaN  25.0       F   mumbai     15/01/2024       180
1         P002  Rahul Sharma  60.0       F    Delhi     2024/01/16       170
2         P003    Neha Singh  45.0       M   Mumbai     2024/01/16       150
3         P004    Neha Singh  60.0    Male  kolkata     15/01/2024       170
4         P005    Neha Singh  25.0    Male  kolkata     2024-01-15       180
..         ...           ...   ...     ...      ...            ...       ...
125       P006   Anita Verma  25.0       M   Mumbai     2024-01-15       150
126       P007    Neha Singh  25.0       F  kolkata     15/01/2024       150
127       P008     John Paul  60.0       F  Chennai     2024-01-15       160
128       P009           NaN  45.0       M   Mumbai     2024-01-15       150
129       P010  Rahul Sharma  60.0  Female  Chennai     2024/01/16       150

[130 rows x 7 columns]

In [10]:
df1=pd.read_csv(r"C:\Users\jainm\OneDrive\ドキュメント\college notes\medical_records.csv")
df1

    record_id patient_id     diagnosis      bp  sugar_level  visit_cost
0        R101       P013  Hypertension  120/80        140.0        2000
1        R102       P105      Diabetes  120/80          NaN        2500
2        R103       P098  Hypertension    high        140.0        3000
3        R104       P038        Asthma  140/90          NaN        3000
4        R105       P040        Asthma  130/85          NaN        1500
..        ...        ...           ...     ...          ...         ...
115      R216       P081        Asthma    high        110.0        2500
116      R217       P033      Diabetes    high          NaN        1500
117      R218       P063  Hypertension  140/90          NaN        2000
118      R219       P011  Hypertension  130/85        180.0        2500
119      R220       P013  Hypertension    high        180.0        1500

[120 rows x 6 columns]

In [11]:
df.describe()

              age
count  106.000000
mean    35.849057
std     21.015546
min     -5.000000
25%     25.000000
50%     30.000000
75%     60.000000
max     60.000000

In [12]:
df.head()

  patient_id          name   age gender     city admission_date height_cm
0       P001           NaN  25.0      F   mumbai     15/01/2024       180
1       P002  Rahul Sharma  60.0      F    Delhi     2024/01/16       170
2       P003    Neha Singh  45.0      M   Mumbai     2024/01/16       150
3       P004    Neha Singh  60.0   Male  kolkata     15/01/2024       170
4       P005    Neha Singh  25.0   Male  kolkata     2024-01-15       180

In [13]:
df.tail()

    patient_id          name   age  gender     city admission_date height_cm
125       P006   Anita Verma  25.0       M   Mumbai     2024-01-15       150
126       P007    Neha Singh  25.0       F  kolkata     15/01/2024       150
127       P008     John Paul  60.0       F  Chennai     2024-01-15       160
128       P009           NaN  45.0       M   Mumbai     2024-01-15       150
129       P010  Rahul Sharma  60.0  Female  Chennai     2024/01/16       150

In [15]:
df.shape

(130, 7)

In [16]:
df.size

910

In [17]:
df.ndim

2

In [18]:
df.isna()

     patient_id   name    age  gender   city  admission_date  height_cm
0         False   True  False   False  False           False      False
1         False  False  False   False  False           False      False
2         False  False  False   False  False           False      False
3         False  False  False   False  False           False      False
4         False  False  False   False  False           False      False
..          ...    ...    ...     ...    ...             ...        ...
125       False  False  False   False  False           False      False
126       False  False  False   False  False           False      False
127       False  False  False   False  False           False      False
128       False   True  False   False  False           False      False
129       False  False  False   False  False           False      False

[130 rows x 7 columns]

In [19]:
df.isna().sum()

patient_id         0
name              23
age               24
gender             0
city               0
admission_date     0
height_cm          0
dtype: int64

In [21]:
df['name'].fillna('riya',inplace=True)

In [22]:
df1['sugar_level'].fillna(0,inplace=True)

In [23]:
df['name'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
125    False
126    False
127    False
128    False
129    False
Name: name, Length: 130, dtype: bool

In [24]:
df

    patient_id          name   age  gender     city admission_date height_cm
0         P001          riya  25.0       F   mumbai     15/01/2024       180
1         P002  Rahul Sharma  60.0       F    Delhi     2024/01/16       170
2         P003    Neha Singh  45.0       M   Mumbai     2024/01/16       150
3         P004    Neha Singh  60.0    Male  kolkata     15/01/2024       170
4         P005    Neha Singh  25.0    Male  kolkata     2024-01-15       180
..         ...           ...   ...     ...      ...            ...       ...
125       P006   Anita Verma  25.0       M   Mumbai     2024-01-15       150
126       P007    Neha Singh  25.0       F  kolkata     15/01/2024       150
127       P008     John Paul  60.0       F  Chennai     2024-01-15       160
128       P009          riya  45.0       M   Mumbai     2024-01-15       150
129       P010  Rahul Sharma  60.0  Female  Chennai     2024/01/16       150

[130 rows x 7 columns]

In [25]:
df1

    record_id patient_id     diagnosis      bp  sugar_level  visit_cost
0        R101       P013  Hypertension  120/80        140.0        2000
1        R102       P105      Diabetes  120/80          0.0        2500
2        R103       P098  Hypertension    high        140.0        3000
3        R104       P038        Asthma  140/90          0.0        3000
4        R105       P040        Asthma  130/85          0.0        1500
..        ...        ...           ...     ...          ...         ...
115      R216       P081        Asthma    high        110.0        2500
116      R217       P033      Diabetes    high          0.0        1500
117      R218       P063  Hypertension  140/90          0.0        2000
118      R219       P011  Hypertension  130/85        180.0        2500
119      R220       P013  Hypertension    high        180.0        1500

[120 rows x 6 columns]